### ISSUE TITLE
Verify test_takeoff_field_length.py and test_landing_field_length.py

### ISSUE THREAD

**Issue by jmvegh** [suavecode/SUAVE#100]
Works with new SUAVE structure, but does not match up with previous results

**Comment by jmvegh** [comment]
Could you please verify the results you had previously?

**Comment by tarikorra** [comment]
sure. 
I'll check the scripts in the regression folder of the develop branch, ok ?

**Comment by jmvegh** [comment]
Great! Thanks Tarik!

----- Original Message -----

**Comment by tarikorra** [comment]
could you please tell me in which folder of which branch is the script you are refering to?

**Comment by tarikorra** [comment]
landing_field_length is ok now. already in the repository.
The difference has due to a change in flaps naming convention from flap_type  to  flaps.type

For the takeoff field, the difference is due to 2 facts:
- We are using now the new engine model, which is different from the one used for the stored results. Also, the input values for the engine are
the ones from B737.
- It looks like the engine model is not using the propulsor.number_of_engines variable, and conisdering always twin engine.

Just for test, I corrected the engine number with a work around in my 'workspace', and the residuals dropped from 5.6e2 to 9.9e1, which can be
associated to the engine model difference.

We must now open an issue for the engine model correction.


Maximum Take OFF Field Length Error= 9.9764e+01

truth_TOFL = np.array ([[  850.19992906,   567.03906016,   411.69975426],
                        [  893.11528215,   592.95224563,   430.3183183 ],
                        [  937.78501446,   619.84892797,   449.62233042],
                        [  984.23928481,   647.73943813,   469.61701137],
                        [ 1032.50914159,   676.63434352,   490.30766781],
                        [ 1082.62653274,   706.54445208,   511.69969462],
                        [ 1134.62431541,   737.48081617,   533.79857721],
                        [ 1188.53626527,   769.45473631,   556.60989361],
                        [ 1244.39708554,   802.47776475,   580.13931657],
                        [ 1302.24241572,   836.56170886,   604.39261547]])

takeoff_field_length = [[  898.63475261   596.27980977   432.70771027]
                        [  945.99509854   624.78409575   453.16201859]
                        [  995.39345529   654.42415696   474.40588135]
                        [ 1046.87251654   685.21579977   496.44786841]
                        [ 1100.47633392   717.17521494   519.29670407]
                        [ 1156.25034215   750.31898623   542.96127143]
                        [ 1214.24138394   784.66409879   567.45061663]
                        [ 1274.49773477   820.22794757   592.77395292]
                        [ 1337.06912755   857.0283455    618.94066483]
                        [ 1402.00677724   895.08353169   645.96031205]]

regards,
Tarik

**Comment by tarikorra** [comment]
**landing_field_length** is now ok. it's already in the repository.
The difference has due to a change in flaps naming convention from **flap_type**  to **flaps.type**

For the takeoff field, the difference is due to 2 facts:
- We are using now the new engine model, which is different from the one used for the stored results. Also, the input values for the engine are the ones from B737.
- It looks like the engine model is not using the **propulsor.number_of_engines** variable, and conisdering always twin engine.

Just for test, I corrected the engine number with a work around in my 'workspace', and the residuals dropped from 5.6e2 to 9.9e1, which can be associated to the engine model difference:

*Maximum Take OFF Field Length Error= 9.9764e+01*

*truth_TOFL = np.array ([[  850.19992906,   567.03906016,   411.69975426],*
*[  893.11528215,   592.95224563,   430.3183183 ],*
*[  937.78501446,   619.84892797,   449.62233042],*
*[  984.23928481,   647.73943813,   469.61701137],*
*[ 1032.50914159,   676.63434352,   490.30766781],*
*[ 1082.62653274,   706.54445208,   511.69969462],*
*[ 1134.62431541,   737.48081617,   533.79857721],*
*[ 1188.53626527,   769.45473631,   556.60989361],*
*[ 1244.39708554,   802.47776475,   580.13931657],*
*[ 1302.24241572,   836.56170886,   604.39261547]])*

*takeoff_field_length = [[  898.63475261   596.27980977   432.70771027]*
*[  945.99509854   624.78409575   453.16201859]*
*[  995.39345529   654.42415696   474.40588135]*
*[ 1046.87251654   685.21579977   496.44786841]*
*[ 1100.47633392   717.17521494   519.29670407]*
*[ 1156.25034215   750.31898623   542.96127143]*
*[ 1214.24138394   784.66409879   567.45061663]*
*[ 1274.49773477   820.22794757   592.77395292]*
*[ 1337.06912755   857.0283455    618.94066483]*
*[ 1402.00677724   895.08353169   645.96031205]]*


regards,
Tarik

**Comment by tarikorra** [comment]
we must now open an issue to address the engine model. It should be using the engine number in order to return total thrust

**Comment by planes** [comment]
Has this been fixed yet?

**Comment by planes** [comment]
These are both in regression now.
